matrix node docs
flojoy-io/docs pull request #59
Opened 2023-06-09 16:24 UTC by Jin1L

2023-06-12 12:16 UTC, smahmed776 requested changes
Left a couple of comments

2023-06-12 12:16 UTC, smahmed776 commented on docs/nodes/GENERATORS/SIMULATIONS/MATRIX/MATRIX.md
> +  GLink='GENERATORS/SIMULATIONS/MATRIX'
This prop is only given when there is no example available to help users to navigate to the node function file.

2023-06-12 12:16 UTC, smahmed776 commented on docs/nodes/GENERATORS/SIMULATIONS/MATRIX/MATRIX.md
> +  GLink='GENERATORS/SIMULATIONS/MATRIX'
`data` props must be provided for `<AppDisplay>` when an example is available

2023-06-19 14:46 UTC, scorinaldi commented
Ok @smahmed776 , looks like @Jin1L made the changes. Could you take another look at this one?

2023-07-13 22:50 UTC, closed without merging